### ISSUE TITLE
Inexplicable Hyper-Acceleration of Entities Upon Collision or Similar Conditions

### ISSUE THREAD

**Issue by steviegt6** [terraprisma/wardian#1]
Entities (confirmed NPCs and players, unsure of whether projectiles are affected) sometimes begin hyper-accelerating at a seemingly arbitrary angle. This is easily observed through town NPCs, but may be observed through things like enemies assuming they don't immediately fling out of the world.

The culprit is commit 30803d74db31cb4e85ecb7dcf78e72f02187c3b2, though I have reviewed all patches made in this commit and nothing seems amiss. I'll address any particular issues with the modified submodule later.

**Comment by steviegt6** [comment]
Figured out, in the auxiliary `Normalize` methods, I don't pass it as `ref`.

**Comment by Smug-B** [comment]
Congrats on figuring it out steviegt6 aka 'tomat'.
